export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const SIGN_UP_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_IN_FAIL";

export const FETCH_USER = "FETCH_USER";

///////// HOUSE ACTION TYPES //////////////

export const ADD_HOUSE_REQUEST = "ADD_HOUSE_REQUEST";
export const ADD_HOUSE_SUCCESS = "ADD_HOUSE_SUCCESS";
export const ADD_HOUSE_FAIL = "ADD_HOUSE_FAIL";

// PROFILE ACTION TYPES 
export const UPDATE_PROFILE_PHOTO_REQ = "UPDATE_PROFILE_PHOTO_REQ";
export const UPDATE_PROFILE_PHOTO_FAIL = "UPDATE_PROFILE_PHOTO_FAIL";
export const UPDATE_PROFILE_PHOTO_SUCCESS = "UPDATE_PROFILE_PHOTO_SUCCESS";

export const UPLOAD_PHOTOS_REQUEST = "UPLOAD_PHOTOS_REQUEST";
export const UPLOAD_PHOTOS_SUCCESS = "UPLOAD_PHOTOS_SUCCESS";
export const UPLOAD_PHOTOS_FAIL = "UPLOAD_PHOTOS_FAIL";

// ROOMMATES
export const ADD_ROOMMATE_REQUEST = "ADD_ROOMMATE_REQUEST";
export const ADD_ROOMMATE_SUCCESS = "ADD_ROOMMATE_SUCCESS";
export const ADD_ROOMMATE_FAIL = "ADD_ROOMMATE_FAIL";


